### ISSUE TITLE
Consider removing the generics on `Loader` methods.

### ISSUE THREAD

**Issue by mscofield0** [XAMPPRocky/fluent-templates#81] opened 2024-09-24 10:31 UTC
Reason for removing would be so that loaders can be used as params (`&dyn Loader`) and so that they can be stored in `Box`es and not have it spew out "not object-safe" errors.

**Comment by XAMPPRocky** [comment] 2024-09-24 11:33
Thank you for your issue! However we already have an issue about this so I'm going to close this a duplicate of https://github.com/XAMPPRocky/fluent-templates/issues/39

**Closed by XAMPPRocky** 2024-09-24 11:33 UTC
